version: "3"

services:
  zoo:
    image: cfei/zookeeper:2.0.0-beta
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      # ZOO_SERVERS: server.1=0.0.0.0:2888:3888,server.2=kafka2.cfei.dk:2888:3888,server.3=kafka3.cfei.dk:2888:3888
      ZOO_AUTHENTICATION: KERBEROS
      KERBEROS_PRINCIPAL: zookeeper/localhost@KAFKA.SECURE
      KERBEROS_PUBLIC_URL: 128.199.53.160
      KERBEROS_REALM: KAFKA.SECURE
      ZOO_REMOVE_HOST_AND_REALM: "true"
    volumes:
      - ./zookeeper.service.keytab:/sasl/zookeeper.service.keytab