version: "3"

services:
  zoo:
    image: omvk97/zookeepertest:0.5.8
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888,server.2=167.172.43.211:2888:$
    volumes:
      - "/data/zookeeper:/data/zookeeper"
    restart: always